name: "${priject.name}"
main: com.github.circularmoonray.addperms.AddPerms
version: ${project.vesion}
author: moonray

commands:
  addperms:
      description: This is add perms.
      usage: /<command> <reload>
      permission: addperms.perms
      permission-message: You don't have <permission>